version: '3'
services:
  mlflow_model_serve:
    image: ghcr.io/r08521610/research-devops:mlflow_model_serve
    volumes:
      - $HOME/.aws:/root/.aws
      - ${PWD}/mlflow_model_serve/.env:/app/.env
    ports:
      - "8000:8000"
