version: '3'
services:
  mlflow_model_serve:
    build:
      context: ./mlflow_model_serve
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:~/.aws
      - .env:.env
    secrets:
      - GIT_ACCESS_TOKEN

secrets:
  GIT_ACCESS_TOKEN:
    external: true