version: '3'
services:
  main:
    container_name: research-devops
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - VARIANT=3.8
        - NODE_VERSION=lts/*
    volumes:
      - .:/workspace:cached
      - ~/.aws:/home/vscode/.aws:cached
      # Persist VS Code extensions between rebuilds
      - vscode-extensions:/root/.vscode-server/extensions
      - ~/.zhistory:/home/vscode/.zhistory:cached
    network_mode: host
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-extensions:
